server:
  port: 8083

## ApiGateway
# id : ???? ???? ?? route id
# uri : ??? ????? ?? URI
# predicates : ?? ???? ??? URI ????, Gateway? ???? ?? URI? ??
spring:
  application:
    name: api-gateway-server
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: order-service
          uri: http://localhost:8082/
          predicates:
            - Path=/order-service/order/product/pro
            - Method=POST
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: order-service
          #          uri: lb://order-service
          uri: http://localhost:8082/
          predicates:
            #            - Path=/api/order/**
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: product-service
          uri: http://localhost:8081/
          predicates:
            - Path=/product-service/**
            - Method=GET
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/user/mailSend
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/user/mailAuthCheck
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/user/signup
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/user/signin
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/user/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/user-service/api/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff